include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Clean Architecture rules
    always_declare_return_types: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    avoid_print: true

    # These are disabled to keep the demo code readable
    public_member_api_docs: false
